---
name: Chaincode Build


on:
  push:
    paths: [chaincode/**]
  pull_request:
    paths: [chaincode/**]


permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chaincode/
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: chaincode/.nvmrc
          cache: npm
          cache-dependency-path: chaincode/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
